language: php

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - DB_CONNECTION=sqlite
    - DB_DATABASE=":memory:"
    - COVERAGE=yes

php:
  - 7.3
  - 7.4snapshot

install:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - |
    if [ $COVERAGE == "yes" ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      travis_retry php ocular.phar code-coverage:upload --format=php-clover coverage.xml
    fi